site_name: MikuAPI

theme:
  name: material

  palette:
    - scheme: default
      primary: deep purple
      accent: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Routing: routing.md
  - Dependency: dependency.md
  - Authentication: auth.md
  - CLI: cli.md