site_name: MikuAPI
site_description: Lightweight Python web framework
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Routing: routing.md
  - Auth: auth.md
  - CLI: cli.md